version: '3'

services:
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - '3002:81'
      - '2003:2003'
      - '8125:8125/udp'
  grafana:
    image: grafana/grafana
    ports:
      - '80:3000'
